### PR TITLE
Perform several fixes and enhancements

### PR DESCRIPTION
**Pull request by Adrianilloo**
Read the commit descriptions carefully.

Thank you.

### CODE REVIEW

**Comment by crashzk** [comment]
I tried compiling to test this version and I get compilation error @Adrianilloo:
```
//SourceMod Batch Compiler
// by the SourceMod Dev Team


//// ServerAdvertisements3.sp
//
// C:\Google Drive\ZK ServidoresÖ\Servidores CSGO\Editar Plugins\addons\sourcemod\scripting\ServerAdvertisements3.sp(82) : error 017: undefined symbol "MAX_AUTHID_LENGTH"
// C:\Google Drive\ZK ServidoresÖ\Servidores CSGO\Editar Plugins\addons\sourcemod\scripting\ServerAdvertisements3.sp(82) : error 161: brackets after variable name indicate a fixed-size array, but a dynamic size was given - did you mean to use 'new char[size]' syntax?
// C:\Google Drive\ZK ServidoresÖ\Servidores CSGO\Editar Plugins\addons\sourcemod\scripting\ServerAdvertisements3.sp(83) : error 130: cannot coerce functions to values
// C:\Google Drive\ZK ServidoresÖ\Servidores CSGO\Editar Plugins\addons\sourcemod\scripting\ServerAdvertisements3.sp(83) : error 163: indeterminate array size in "sizeof" expression (symbol "authId")
// C:\Google Drive\ZK ServidoresÖ\Servidores CSGO\Editar Plugins\addons\sourcemod\scripting\ServerAdvertisements3.sp(86) : error 130: cannot coerce functions to values
// C:\Google Drive\ZK ServidoresÖ\Servidores CSGO\Editar Plugins\addons\sourcemod\scripting\ServerAdvertisements3.sp(99) : error 017: undefined symbol "MAX_AUTHID_LENGTH"
// C:\Google Drive\ZK ServidoresÖ\Servidores CSGO\Editar Plugins\addons\sourcemod\scripting\ServerAdvertisements3.sp(99) : error 161: brackets after variable name indicate a fixed-size array, but a dynamic size was given - did you mean to use 'new char[size]' syntax?
// C:\Google Drive\ZK ServidoresÖ\Servidores CSGO\Editar Plugins\addons\sourcemod\scripting\ServerAdvertisements3.sp(100) : error 130: cannot coerce functions to values
// C:\Google Drive\ZK ServidoresÖ\Servidores CSGO\Editar Plugins\addons\sourcemod\scripting\ServerAdvertisements3.sp(100) : error 163: indeterminate array size in "sizeof" expression (symbol "authId")
// C:\Google Drive\ZK ServidoresÖ\Servidores CSGO\Editar Plugins\addons\sourcemod\scripting\ServerAdvertisements3.sp(101) : error 130: cannot coerce functions to values
//
// 10 Errors.
//
// Compilation Time: 0,3 sec
// ----------------------------------------

Press enter to exit ...
```

SourceMod: 1.10 - build 6528

**Comment by Adrianilloo** [comment]
@crashzk Fixed your mentioned compilation error. This was due to me having used SourcePawn 1.11 to compile, since which introduced the new `MAX_AUTHID_LENGTH` macro that I didn't know of until recently.

**Comment by crashzk** [comment]
> @crashzk Fixed your mentioned compilation error. This was due to me having used SourcePawn 1.11 to compile, since which introduced the new `MAX_AUTHID_LENGTH` macro that I didn't know of until recently.

Thanks, yes, then I tried compiling on sourcemod version 1.11 and it went normally. In any case, thanks for making it compatible with SM 1.10 as well.

Without wanting to abuse your goodwill, but if you do, it would be possible for you to take a look at these two suggestions:

- https://github.com/ESK0/ServerAdvertisement3/issues/17
- https://github.com/ESK0/ServerAdvertisement3/issues/15

Would it be possible to implement them? If so, I could, if you want, I can make a donation for the work.

In any case, thanks again for the work so far, I'll be testing this version, any problems let me know here.

**Comment by Adrianilloo** [comment]
I think these aren't hard features to make, so I'll see if I have the motivation and time. However, it would be interesting for @ESK0 to check this PR too.

**Comment by crashzk** [comment]
@Adrianilloo I believe I found a bug with the random function implemented.

It works all right, but it happened on my server that it repeated the message.

image

Plugin sent the same message with the random option active.

**Comment by Adrianilloo** [comment]
I've checked the randomization code and it is not just correct, but minimum. What you got is a valid possibility from odds.

I'm going to start coding your two requested features as I find them useful and simple :)

**Comment by crashzk** [comment]
> I've checked the randomization code and it is not just correct, but minimum. What you got is a valid possibility from odds.

I understand, I even imagined that, from what I've noticed is something rare, but it can happen.

> I'm going to start coding your two requested features as I find them useful and simple :)

Regarding this, a friend helped me implement the following feature:
- https://github.com/ESK0/ServerAdvertisement3/issues/15

I'll do a PR on yours and if you take a look if it pleases you we can eliminate this one and focus on the other, option to configure time for each message individually.

**[EDIT]**
Never mind, you already did too.

**Comment by Adrianilloo** [comment]
@crashzk Updated PR with latest changes from #17, also along new plugin version (`3.3.0`) for convenience.

I've finished the full revision of recent changes as planned and adjusted just few details, mostly stylish. With this small enhancement: new `{TAG}` token replacements will have color tags (e.g. `{green}` and such) stripped for non-chat display elements, as these don't support HEX color codes (i.e. HUD, white center text, top menu). Live example:

```
"8"
{
	"tag"	"{green}[TAG]"
	"type"	"M"
	"en"	"{TAG} Play, be respectful and enjoy!"
	"es"	"{TAG} ¡Juega, sé respetuoso y diviértete!"
	"color"	"255 165 0 255"
	"posY"	"0.015"
	"time"	"10"
}
```


As usual, please compile this PR version (or my [`master`](https://github.com/Adrianilloo/ServerAdvertisement3) branch) and let me know if all works well. Anything that ever remains imperfect I'll fix.

Finally, I've added a donation link in my profile if you finally feel like contributing a bit for my work. Thank you!

**Comment by crashzk** [comment]
@Adrianilloo perfect, I'll be testing these modifications.

Yes, I sent a value yes, small but from the heart for your great help. And I'm more than happy to keep in touch with you in case you need a developer in the future to fix some plugins and always with a contribution, however small.

**Comment by crashzk** [comment]
@Adrianilloo so far so good, just a suggestion, in the visual case I believe.

Plugin no longer supports MySQL, but still has the option in the config:
```
"Settings"
{
	"ServerName"			"{default}[ {darkred}TAG {default}]"			// Server tag
	"ServerType"			"default"			// Only if MySQL is 1 -> Simply divide messages to groups (e.g. 3 servers uses ServerType surf and 2 servers uses jailbreak)
	"Time"				"35.0"			// Time in seconds
	"Random"			"1"			// Whether to randomize order of messages
	"Languages"			"PT"			// List of languages / Keep the main language first (If player connect from Country you did not translated. He will get messages in language which is the first in list).
	"Default language"		"ingame"			// Value = "geoip" or "ingame"
	"Log expired messages"		"0"			// 1 = Enabled -> Messages are loged in Sourcemod's error log
}
```

```
"ServerType"	"default"	// Only if MySQL is 1 -> Simply divide messages to groups (e.g. 3 servers uses ServerType surf and 2 servers uses jailbreak)
```

I believe that all this information regarding MySQL support in the plugin source file and in the configuration can be deleted, correct?

image

**Comment by Adrianilloo** [comment]
@crashzk I have cleaned that unused variable and squashed the commits since the MySQL clean one. Didn't notice, nice catch.

MySQL support was marked as TODO from @ESK0 long time ago in the original [AM post](https://forums.alliedmods.net/showthread.php?p=2199152), but I think we can agree it's unneeded so it's better off removing the traits.

**Comment by Adrianilloo** [comment]
@ESK0 Would you be able to revise and/or accept this? We've been at least two testers.

Thanks.

**Pull request merged**
